name: Stanford1
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
  - python==3.5.2
  - Cython=0.23.4
  - Jinja2=2.8
  - MarkupSafe=0.23
  - Pillow
  - Pygments=2.0.2
  - cycler=0.10.0
  - decorator=4.0.6
  - future=0.16.0
  - ipykernel=4.2.2
  - ipython=4.0.1
  - ipywidgets=4.1.1
  - jsonschema
  - jupyter
  - matplotlib
  - mistune=0.7.1
  - nbconvert=4.1.0
  - nbformat=4.0.1
  - notebook=4.0.6
  - numpy
  - path.py=8.1.2
  - pexpect
  - pickleshare=0.5
  - python-dateutil=2.4.2
  - pytz
  - pyzmq=15.1.0
  - qtconsole=4.1.1
  - scipy
  - simplegeneric=0.8.1
  - singledispatch=3.4.0.3
  - six=1.10.0
  - tornado=4.3
  - traitlets=4.0.0
